### ISSUE TITLE
能区分开发环境么

### ISSUE THREAD

**Issue by daizhengqing** [vincent-cy/check-update#1]
本地开发热更新时也会触发，不太方便

**Comment by vincent-cy** [comment]
Judgment can be made at the place where this method is injected. Determine whether initialization is required based on the current environment.

For projects built with vite:

![35eb0384-8f27-4157-865f-234f2dc2fe38](https://user-images.githubusercontent.com/21096802/213339805-bd5990e3-4bff-4814-b5b7-2d210bdb5419.png)

**Comment by vincent-cy** [comment]
Judgment can be made at the place where this method is injected. Determine whether initialization is required based on the current environment.

For projects built with vite:

![35eb0384-8f27-4157-865f-234f2dc2fe38](https://user-images.githubusercontent.com/21096802/213339805-bd5990e3-4bff-4814-b5b7-2d210bdb5419.png)

**Comment by Ryan-cyi** [comment]
Judgment can be made at the place where this method is injected. Determine whether initialization is required based on the current environment.

For projects built with vite:
![image](https://user-images.githubusercontent.com/21096802/213340202-707f238f-932a-4789-9694-4aa5c756d08c.png)
